services:
  gateway_service:
    build: ./gateway_service
    container_name: gateway_service
    ports:
      - "8080:8000"
    environment:
      - INGESTION_SERVICE_URL=http://ingestion_service:8000
      - STORAGE_SERVICE_URL=http://storage_service:8001
      - ANALYSIS_SERVICE_URL=http://analysis_service:8002
    depends_on:
      - ingestion_service
      - storage_service
      - analysis_service

  ingestion_service:
    build: ./ingestion_service
    container_name: ingestion_service
    ports:
      - "8000:8000"
    env_file:
      - ./ingestion_service/.env

  storage_service:
    build: ./storage_service
    container_name: storage_service
    ports:
      - "8001:8001"
    env_file:
      - ./storage_service/.env
    volumes:
      - ./storage:/app/storage
      - ./chroma_db:/app/chroma_db
    depends_on:
      - postgres

  analysis_service:
    build: ./analysis_service
    container_name: analysis_service
    ports:
      - "8002:8002"
    env_file:
      - ./analysis_service/.env

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  storage:
  chroma_db:
