version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  storage_service:
    build: ./storage_service
    ports:
      - "8001:8001"
    env_file:
      - ./storage_service/.env
    volumes:
      - ./storage:/app/storage
      - ./chroma_db:/app/chroma_db
    depends_on:
      - postgres

  gateway_service:
    build: ./gateway_service
    ports:
      - "8080:8000"
    environment:
      - INGESTION_SERVICE_URL=http://ingestion_service:8000
      - STORAGE_SERVICE_URL=http://storage_service:8001
      - ANALYSIS_SERVICE_URL=http://host.docker.internal:8002
    depends_on:
      - storage_service

volumes:
  postgres_data:
  storage:
  chroma_db: